name: Build http-server docker image
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU for multi arch builds
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build images
        run: chmod u+x build.sh && ./build.sh